export const ENV_VARS = {
  MAPTILER_KEY: 'MAPTILER_KEY',
  MAPTILER_MAP_ID_VOYAGER: 'MAPTILER_MAP_ID_VOYAGER',
  MAPTILER_MAP_ID_LIGHT: 'MAPTILER_MAP_ID_LIGHT',
  MAPTILER_MAP_ID_LABELS: 'MAPTILER_MAP_ID_LABELS',
  MAPTILER_MAP_ID_BORDERS: 'MAPTILER_MAP_ID_BORDERS',
  MAPTILER_MAP_ID_ROADS: 'MAPTILER_MAP_ID_ROADS',
  GEO_DB_CLIENT_ID: 'GEO_DB_CLIENT_ID',
  GEO_DB_CLIENT_SECRET: 'GEO_DB_CLIENT_SECRET',
  SH_CLIENT_ID: 'SH_CLIENT_ID',
  SH_CLIENT_SECRET: 'SH_CLIENT_SECRET',
};

const ENV_VAR_NAMES = {
  MAPTILER_KEY: {
    buildTimeName: 'REACT_APP_MAPTILER_KEY',
    runTimeName: 'REACT_APP_MAPTILER_KEY',
  },
  MAPTILER_MAP_ID_VOYAGER: {
    buildTimeName: 'REACT_APP_MAPTILER_MAP_ID_VOYAGER',
    runTimeName: 'REACT_APP_MAPTILER_MAP_ID_VOYAGER',
  },
  MAPTILER_MAP_ID_LIGHT: {
    buildTimeName: 'REACT_APP_MAPTILER_MAP_ID_LIGHT',
    runTimeName: 'REACT_APP_MAPTILER_MAP_ID_LIGHT',
  },
  MAPTILER_MAP_ID_LABELS: {
    buildTimeName: 'REACT_APP_MAPTILER_MAP_ID_LABELS',
    runTimeName: 'REACT_APP_MAPTILER_MAP_ID_LABELS',
  },
  MAPTILER_MAP_ID_BORDERS: {
    buildTimeName: 'REACT_APP_MAPTILER_MAP_ID_BORDERS',
    runTimeName: 'REACT_APP_MAPTILER_MAP_ID_BORDERS',
  },
  MAPTILER_MAP_ID_ROADS: {
    buildTimeName: 'REACT_APP_MAPTILER_MAP_ID_ROADS',
    runTimeName: 'REACT_APP_MAPTILER_MAP_ID_ROADS',
  },
  GEO_DB_CLIENT_ID: {
    buildTimeName: 'REACT_APP_GEO_DB_CLIENT_ID',
    runTimeName: 'GEODB_AUTH_CLIENT_ID',
  },
  GEO_DB_CLIENT_SECRET: {
    buildTimeName: 'REACT_APP_GEO_DB_CLIENT_SECRET',
    runTimeName: 'GEODB_AUTH_CLIENT_SECRET',
  },
  SH_CLIENT_ID: {
    buildTimeName: 'REACT_APP_SH_CLIENT_ID',
    runTimeName: 'SH_CLIENT_ID',
  },
  SH_CLIENT_SECRET: {
    buildTimeName: 'REACT_APP_SH_CLIENT_SECRET',
    runTimeName: 'SH_CLIENT_SECRET',
  },
};

export function getEnvVarValue(envVar) {
  return process.env[ENV_VAR_NAMES[envVar].buildTimeName]
    ? process.env[ENV_VAR_NAMES[envVar].buildTimeName]
    : window._env_[ENV_VAR_NAMES[envVar].runTimeName];
}
