export const translatedCollectionIds = {
  'sentinel-s2-l2a-mosaic-120': 'SENTINEL2_L2A_MOSAIC_120',
  'copernicus-dem': 'COPERNICUS_30',
  'mapzen-dem': 'MAPZEN_DEM',
  'sentinel-1-grd': 'SENTINEL1_GRD',
  '2mt_2020_monthly_average_from_cds': 'CDS_2M_TEMP_2020',
  'alos-2-palsar-2-scansar-rice-fields-map': 'ALOS_PALSAR2_RICE_PADDY_FIELD_MAP',
  'alos-2-palsar-2-scansar-for-agriculture': 'ALOS_PALSAR2_AGRICULTURE',
  'alos-2-palsar-2-stripmap-for-economy-sm1': 'ALOS_PALSAR2_L2_1_3M',
  'alos-2-palsar-2-stripmap-for-economy': 'ALOS_PALSAR2_L2_1_10M',
  cams_glc_2017: 'CAMS_GLC',
  chl_water_quality_saturday: 'CNR_CHL',
  'cnes-land-cover-map': 'CNES_LAND_COVER_MAP',
  'corine-land-cover': 'CORINE_LAND_COVER',
  'corine-land-cover-accounting-layers': 'CORINE_LAND_COVER_ACCOUNTING_LAYERS',
  e12c_motorway: 'E12C_MOTORWAY',
  e12d_primary_corrected: 'E12D_PRIMARY',
  worldcover: 'ESA_WORLDCOVER_10M_2020_V1',
  'global-human-settlement-layer-ghs-built-s2': 'GHS_BUILT_S2',
  'global-land-cover': 'GLOBAL_LAND_COVER',
  'global-surface-water': 'GLOBAL_SURFACE_WATER',
  iceye_e11: 'ICEYE_GRD_E11',
  iceye_e11a: 'ICEYE_GRD_E11A',
  iceye_e13b: 'ICEYE_GRD_E13B',
  iceye_e3: 'ICEYE_GRD_E3',
  jaxa_wq_chla: 'JAXA_WQ_CHLA_ANOMALY',
  jaxa_wq_chla_average: 'JAXA_WQ_CHLA_AVERAGE',
  jaxa_wq_tsm: 'JAXA_WQ_TSM_ANOMALY',
  jaxa_wq_tsm_average: 'JAXA_WQ_TSM_AVERAGE',
  'landsat-1-5-mss-l1': 'LANDSAT1-5_MSS_L1',
  'landsat-4-5-tm-l1': 'LANDSAT4-5_TM_L1',
  'landsat-4-5-tm-l2': 'LANDSAT4-5_TM_L2',
  'landsat-7-etm+l1': 'LANDSAT7_ETM_L1',
  'landsat-7-etm+l2': 'LANDSAT7_ETM_L2',
  'landsat-8-l1': 'LANDSAT8-9_L1',
  'landsat-8-l2': 'LANDSAT8-9_L2',
  modis: 'MODIS',
  population_density: 'POPULATION_DENSITY',
  's5p-no2-tropno-daily-check': 'SENTINEL_5P_NO2_T14D_AVERAGE',
  'sea-ice-index': 'SEA_ICE_INDEX',
  'seasonal-trajectories': 'SEASONAL_TRAJECTORIES',
  card4l: 'SENTINEL1_CARD4L',
  'sentinel-2-l1c': 'SENTINEL2_L1C_SENTINELHUB',
  'sentinel-2-l2a': 'SENTINEL2_L2A_SENTINELHUB',
  'sentinel-3-l1b-olci': 'SENTINEL3_OLCI_L1B',
  'sentinel-3-l1b-slstr': 'SENTINEL3_SLSTR',
  'sentinel-5p-l2-tropomi': 'SENTINEL_5P_L2',
  tsmn_water_quality_saturday: 'CNR_TSM',
  'vegetation-indices': 'VEGETATION_INDICES',
  'vegetation-phenology-and-productivity-parameters-season-1':
    'VEGETATION_PHENOLOGY_AND_PRODUCTIVITY_PARAMETERS_SEASON_1',
  'vegetation-phenology-and-productivity-parameters-season-2':
    'VEGETATION_PHENOLOGY_AND_PRODUCTIVITY_PARAMETERS_SEASON_2',
  vessel_density_all: 'EMODNET_VESSEL_DENSITY',
  vessel_density_cargo: 'EMODNET_VESSEL_DENSITY_CARGO',
  vessel_density_other: 'EMODNET_VESSEL_DENSITY_OTHER',
  vessel_density_tanker: 'EMODNET_VESSEL_DENSITY_TANKER',
  'water-bodies': 'WATER_BODIES',
  wind_10m_u: 'ERA5_WIND_U',
  wind_10m_v: 'ERA5_WIND_V',
};
